package org.vitrivr.engine.index.exporters

import com.github.kokorin.jaffree.StreamType
import com.github.kokorin.jaffree.ffmpeg.FFmpeg
import com.github.kokorin.jaffree.ffmpeg.UrlInput
import com.github.kokorin.jaffree.ffmpeg.UrlOutput
import com.github.kokorin.jaffree.ffprobe.FFprobe
import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.onEach
import org.vitrivr.engine.core.context.Context
import org.vitrivr.engine.core.model.retrievable.Retrievable
import org.vitrivr.engine.core.model.retrievable.attributes.SourceAttribute
import org.vitrivr.engine.core.operators.Operator
import org.vitrivr.engine.core.operators.OperatorFactory
import org.vitrivr.engine.core.operators.general.Exporter
import org.vitrivr.engine.core.resolver.PathResolver
import org.vitrivr.engine.core.source.MediaType
import org.vitrivr.engine.core.source.file.FileSource
import java.nio.file.Files
import java.nio.file.Path
import kotlin.math.roundToInt

/**
 * An [Exporter] that generates HTTP Live Streaming (HLS) representations for video sources.
 * For each video source the exporter creates multiple renditions (currently 480p and 1080p) and a master
 * playlist referencing them.
 *
 * The resulting directory structure is:
 *
 * ```
 * <resolver-root>/
 * └── <source-id>/
 *     ├── master.m3u8
 *     ├── 480/
 *     │   ├── playlist.m3u8
 *     │   ├── segment_000.ts
 *     │   └── ...
 *     └── 1080/
 *         ├── playlist.m3u8
 *         ├── segment_000.ts
 *         └── ...
 * ```
 *
 * Author Andrina Geller
 * @version 1.0.0
 */

class HlsVideoExporter : OperatorFactory {

    /**
     * Creates a new HLS exporter operator.
     *
     * @param name this operator instance.
     * @param inputs Map of named input [Operator]s
     * @param context The [Context] to use.
     */
    override fun newOperator(
        name: String, inputs: Map<String, Operator<out Retrievable>>, context: Context
    ): Operator<out Retrievable> {
        require(inputs.size == 1) { "HlsVideoExporter requires exactly one input." }

        val segmentDuration = context[name, "segmentDuration"]?.toDoubleOrNull() ?: 6.0
        val preset = context[name, "preset"] ?: "medium"
        val ffmpegPath = context[name, "ffmpegPath"]?.let { Path.of(it) }
        val resolverName = context[name, "resolver"] ?: "default"
        val resolver = context.resolver[resolverName] ?: context.schema.getResolver(resolverName)

        require(resolver is PathResolver) { "HlsVideoExporter requires a PathResolver, " + "but '$resolverName' is ${resolver::class.qualifiedName}." }

        return Instance(
            name = name,
            input = inputs.values.first(),
            outputRoot = resolver.root,
            segmentDuration = segmentDuration,
            preset = preset,
            ffmpegPath = ffmpegPath
        )
    }

    /**
     * The [Exporter] generated by this [HlsVideoExporter].
     */
    private class Instance(
        override val name: String,
        override val input: Operator<out Retrievable>,
        private val outputRoot: Path,
        private val segmentDuration: Double,
        private val preset: String,
        private val ffmpegPath: Path?
    ) : Exporter {

        private val logger: KLogger = KotlinLogging.logger {}

        /**
         * Creates a FFMpeg instance
         */
        private val ffmpeg: FFmpeg
            get() = if (ffmpegPath != null) {
                FFmpeg.atPath(ffmpegPath)
            } else {
                FFmpeg.atPath()
            }

        /**
         * Creates an FFprobe instance
         */
        private val ffprobe: FFprobe
            get() = if (ffmpegPath != null) {
                FFprobe.atPath(ffmpegPath)
            } else {
                FFprobe.atPath()
            }


        /**
         * Configuation for a single quality level (e.g. 480p or 1080p).
         * @name rendition identifier
         * @height of video in pixels
         * @videoBitrate average target video bitrate
         * @maxRate maximum bitrate
         * @bufferSize rate-control buffer size
         * @audioBitrate AAC audio bitrate
         * @bandwidth estimated peak bandwidth written to the HLS master playlist
         */
        private data class Rendition(
            val name: String,
            val height: Int,
            val videoBitrate: String,
            val maxRate: String,
            val bufferSize: String,
            val audioBitrate: String,
            val bandwidth: Int
        )

        /**
         * Generates the HLS renditions for every source video.
         */
        private val renditions = listOf(
            Rendition(
                name = "480",
                height = 480,
                videoBitrate = "800k",
                maxRate = "900k",
                bufferSize = "1800k",
                audioBitrate = "96k",
                bandwidth = ((900_000 + 96_000) * 1.10).roundToInt()
            ), Rendition(
                name = "1080",
                height = 1080,
                videoBitrate = "5000k",
                maxRate = "5500k",
                bufferSize = "11000k",
                audioBitrate = "128k",
                bandwidth = ((5_500_000 + 128_000) * 1.10).roundToInt()
            )
        )

        /**
         * Processes retrievables passing through the exporter.
         * Generates the HLS representations and forwards the retrievable unchanged.
         * Only video sources are processed (segments are skipped).
         */
        override fun toFlow(scope: CoroutineScope): Flow<Retrievable> = input.toFlow(scope).onEach { retrievable ->
            val source = retrievable.filteredAttribute(SourceAttribute::class.java)?.source ?: return@onEach
            if (source.type != MediaType.VIDEO) {
                return@onEach
            }

            if (retrievable.type == "SEGMENT") {
                return@onEach
            }

            if (source !is FileSource) {
                logger.warn { "HLS generation currently only supports FileSource: ${source.name}" }
                return@onEach
            }

            try {
                generateHls(source)
            } catch (e: Throwable) {
                logger.error(e) { "Failed generating HLS for ${source.name} (${source.sourceId})." }
            }
        }.flowOn(Dispatchers.IO)

        /**
         * Generates the HLS representation for a video.
         * The source UUID is used as the folder name.
         */
        private fun generateHls(source: FileSource) {
            val root = outputRoot.resolve(source.sourceId.toString())
            Files.createDirectories(root)
            val fps = determineFps(source)
            val gop = (fps * segmentDuration).roundToInt().coerceAtLeast(1)
            for (rendition in renditions) {
                generateRendition(source, root, rendition, gop)
            }
            writeMasterPlaylist(root)
        }

        /**
         * Determines the frame rate of a source video using FFmpeg.
         *
         * @throws IllegalStateException if no video stream exists.
         */
        private fun determineFps(source: FileSource): Double {
            val result = ffprobe.setShowStreams(true).setInput(source.path).execute()
            val stream = result.streams.firstOrNull { it.codecType == StreamType.VIDEO }
                ?: error("No video stream found in ${source.path}")
            return stream.avgFrameRate.toDouble()
        }

        /**
         * Generates one HLS rendition with FFmpeg.
         */
        private fun generateRendition(source: FileSource, root: Path, rendition: Rendition, gop: Int) {
            val directory = root.resolve(rendition.name)
            Files.createDirectories(directory)
            val playlist = directory.resolve("playlist.m3u8")
            val output = UrlOutput.toPath(playlist).addArguments("-map", "0:v:0").addArguments("-map", "0:a:0?")
                .addArguments("-vf", "scale=-2:${rendition.height}").addArguments("-c:v", "libx264")
                .addArguments("-preset", preset).addArguments("-b:v", rendition.videoBitrate)
                .addArguments("-maxrate", rendition.maxRate).addArguments("-bufsize", rendition.bufferSize)
                .addArguments("-g", gop.toString()).addArguments("-keyint_min", gop.toString())
                .addArguments("-sc_threshold", "0")
                .addArguments("-force_key_frames", "expr:gte(t,n_forced*$segmentDuration)").addArguments("-c:a", "aac")
                .addArguments("-b:a", rendition.audioBitrate).setFormat("hls")
                .addArguments("-hls_time", segmentDuration.toString()).addArguments("-hls_playlist_type", "vod")
                .addArguments("-hls_flags", "independent_segments")
                .addArguments("-hls_segment_filename", directory.resolve("segment_%03d.ts").toString())

            ffmpeg.addInput(UrlInput.fromPath(source.path)).setOverwriteOutput(true).addOutput(output).execute()
        }

        /**
         * Creates the HLS master playlist.
         */
        private fun writeMasterPlaylist(root: Path) {
            val master = buildString {
                appendLine("#EXTM3U")
                appendLine("#EXT-X-VERSION:3")
                appendLine()

                for (rendition in renditions) {
                    appendLine("#EXT-X-STREAM-INF:BANDWIDTH=${rendition.bandwidth}")
                    appendLine("${rendition.name}/playlist.m3u8")
                    appendLine()
                }
            }
            Files.writeString(
                root.resolve("master.m3u8"), master
            )
        }
    }
}