package org.vitrivr.engine.index.exporters

import com.sksamuel.scrimage.ImmutableImage
import com.sksamuel.scrimage.nio.JpegWriter
import com.sksamuel.scrimage.nio.PngWriter
import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.onEach
import org.vitrivr.engine.core.context.IndexContext
import org.vitrivr.engine.core.model.content.element.ImageContent
import org.vitrivr.engine.core.model.retrievable.Retrievable
import org.vitrivr.engine.core.operators.Operator
import org.vitrivr.engine.core.operators.general.Exporter
import org.vitrivr.engine.core.operators.general.ExporterFactory
import org.vitrivr.engine.core.resolver.Resolver
import org.vitrivr.engine.core.source.file.MimeType

private val logger: KLogger = KotlinLogging.logger {}

/**
 * An [Exporter] that generates thumbnails from videos and images.
 *
 * @author Finn Faber
 * @version 1.0.2
 */
class ThumbnailExporter : ExporterFactory {
    companion object {
        val SUPPORTED = setOf(MimeType.JPEG, MimeType.JPG, MimeType.PNG)
    }

    /**
     * Creates a new [Exporter] instance from this [ThumbnailExporter].
     *
     * @param name The name of the [Exporter]
     * @param input The [Operator] to acting as an input.
     * @param context The [IndexContext] to use.
     */
    override fun newExporter(name: String, input: Operator<Retrievable>, context: IndexContext): Exporter {
        val resolverName = context[name, "resolver"]?: "default"
        val maxSideResolution = context[name, "maxSideResolution"]?.toIntOrNull() ?: 400
        val mimeType = context[name, "mimeType"]?.let {
            try {
                MimeType.valueOf(it.uppercase())
            } catch (e: java.lang.IllegalArgumentException) {
                null
            }
        } ?: MimeType.JPG
        logger.debug { "Creating new ThumbnailExporter with maxSideResolution=$maxSideResolution and mimeType=$mimeType." }
        return Instance(input, context, resolverName, maxSideResolution, mimeType, name)
    }

    /**
     * The [Exporter] generated by this [ThumbnailExporter].
     */
    private class Instance(
        override val input: Operator<Retrievable>,
        private val context: IndexContext,
        resolverName: String,
        private val maxResolution: Int,
        private val mimeType: MimeType,
        override val name: String
    ) : Exporter {
        init {
            require(mimeType in SUPPORTED) { "ThumbnailExporter only support image formats JPEG and PNG." }
        }

        /** [Resolver] instance. */
        private val resolver: Resolver = this.context.resolver[resolverName] ?: throw IllegalStateException("Unknown resolver with name $resolverName.")

        /** [KLogger] instance. */
        private val logger: KLogger = KotlinLogging.logger {}

        override fun toFlow(scope: CoroutineScope): Flow<Retrievable> = this.input.toFlow(scope).onEach { retrievable ->
            try {
                val resolvable = this.resolver.resolve(retrievable.id, ".${this.mimeType.fileExtension}")
                val content = retrievable.content.filterIsInstance<ImageContent>()
                if (resolvable != null && content.isNotEmpty()) {
                    val writer = when (mimeType) {
                        MimeType.JPEG,
                        MimeType.JPG -> JpegWriter()
                        MimeType.PNG -> PngWriter()
                        else -> throw IllegalArgumentException("Unsupported mime type $mimeType")
                    }

                    logger.debug { "Generating thumbnail(s) for ${retrievable.id} with ${retrievable.type} and resolution $maxResolution. Storing it with ${resolvable::class.simpleName}." }

                    content.forEach { cnt ->
                        val imgBytes = ImmutableImage.fromAwt(cnt.content).let {
                            if (it.width > it.height) {
                                it.scaleToWidth(maxResolution)
                            } else {
                                it.scaleToHeight(maxResolution)
                            }
                        }.bytes(writer)

                        resolvable.openOutputStream().use {
                            it.write(imgBytes)
                        }
                    }
                }
            } catch (e: Exception) {
                logger.error(e){"Error during thumbnail creation"}
            }
        }
    }
}

