package org.vitrivr.engine.index.exporters

import com.sksamuel.scrimage.ImmutableImage
import com.sksamuel.scrimage.nio.JpegWriter
import com.sksamuel.scrimage.nio.PngWriter
import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.onEach
import org.bytedeco.javacpp.PointerScope
import org.bytedeco.javacv.FFmpegFrameGrabber
import org.bytedeco.javacv.Java2DFrameConverter
import org.vitrivr.engine.core.context.Context
import org.vitrivr.engine.core.model.retrievable.Retrievable
import org.vitrivr.engine.core.model.retrievable.attributes.SourceAttribute
import org.vitrivr.engine.core.operators.Operator
import org.vitrivr.engine.core.operators.OperatorFactory
import org.vitrivr.engine.core.operators.general.Exporter
import org.vitrivr.engine.core.resolver.Resolver
import org.vitrivr.engine.core.source.MediaType
import org.vitrivr.engine.core.source.file.MimeType
import java.awt.image.BufferedImage
import java.io.InputStream
import kotlin.text.toIntOrNull
import kotlin.text.uppercase


private val logger: KLogger = KotlinLogging.logger {}

/**
 * An [Exporter] that generates a single preview of a video at the parameterized timestamp.
 *
 * @author Rahel Arnold
 * @version 2.2.0
 */
class VideoPreviewExporter : OperatorFactory {
    companion object {
        val SUPPORTED = setOf(MimeType.JPEG, MimeType.JPG, MimeType.PNG)
    }

    /**
     * Creates a new [Instance] instance from this [ThumbnailExporter].
     *
     * @param name the name of the [ThumbnailExporter.Instance]
     * @param inputs Map of named input [Operator]s
     * @param context The [Context] to use.
     */
    override fun newOperator(name: String, inputs: Map<String, Operator<out Retrievable>>, context: Context): Operator<out Retrievable> {
        require(inputs.size == 1)  { "The ${this::class.simpleName} only supports one input operator. If you want to combine multiple inputs, use explicit merge strategies." }
        val resolverName = context[name, "resolver"] ?: "default"
        val maxSideResolution = context[name, "maxSideResolution"]?.toIntOrNull() ?: 400
        val mimeType =
            context[name, "mimeType"]?.let {
                try {
                    MimeType.valueOf(it.uppercase())
                } catch (_: java.lang.IllegalArgumentException) {
                    null
                }
            } ?: MimeType.JPG
        val previewTimeSec =  context[name, "previewTimeSec"]?.toIntOrNull() ?: 5
        return Instance(name, inputs.values.first(), context, resolverName, maxSideResolution, mimeType, previewTimeSec)
    }

    /** The [Exporter] generated by this [VideoPreviewExporter]. */
    private class Instance(
        override val name: String,
        override val input: Operator<out Retrievable>,
        private val context: Context,
        resolverName: String,
        private val maxResolution: Int,
        private val mimeType: MimeType,
        private val previewTimeSec: Int,
    ) : Exporter {
        init {
            require(mimeType in SUPPORTED) {
                "VideoPreviewExporter only supports image formats JPEG and PNG."
            }
        }

        /** [Resolver] instance. */
        private val resolver: Resolver = this.context.resolver[resolverName]
            ?: throw IllegalStateException("Unknown resolver with name $resolverName.")


        override fun toFlow(scope: CoroutineScope): Flow<Retrievable> = this.input.toFlow(scope).onEach { retrievable ->
            val source = retrievable.filteredAttribute(SourceAttribute::class.java)?.source ?: return@onEach
            if (source.type == MediaType.VIDEO) {
                val resolvable = this.resolver.resolve(retrievable.id,this.mimeType.fileExtension)
                if (resolvable != null) {
                    val writer = when (mimeType) {
                        MimeType.JPEG,
                        MimeType.JPG -> JpegWriter()

                        MimeType.PNG -> PngWriter()
                        else -> throw IllegalArgumentException("Unsupported mime type $mimeType")
                    }

                    logger.debug {
                        "Generating preview thumbnail for ${retrievable.id} with ${retrievable.type} and resolution $maxResolution. Storing it with ${resolvable::class.simpleName}."
                    }

                    source.newInputStream().use { input ->
                        val frame = getFrameAtSecond(input, previewTimeSec)
                        val imgBytes = ImmutableImage.fromAwt(frame).let {
                            if (it.width > it.height) {
                                it.scaleToWidth(maxResolution)
                            } else {
                                it.scaleToHeight(maxResolution)
                            }
                        }.bytes(writer)

                        resolvable.openOutputStream().use { output ->
                            output.write(imgBytes)
                        }
                    }
                }
            }
        }

        /**
         * Extracts a frame from the video at the specified second.
         *
         * @param input The [InputStream] representing the vide file.
         * @param second The second at which to extract the frame.
         * @return The extracted frame as a BufferedImage.
         */
        private fun getFrameAtSecond(input: InputStream, second: Int): BufferedImage {
            FFmpegFrameGrabber(input).use { grabber ->
                grabber.start()
                val frameRate = grabber.frameRate
                grabber.frameNumber = (frameRate * second).toInt()

                val frame = grabber.grabImage() ?: throw IllegalStateException("Could not grab frame from video.")

                val img = try {
                    PointerScope().use { scope ->
                        val c = Java2DFrameConverter()
                        c.convert(frame)
                    }
                } catch (e: Exception) {
                    logger.error(e) { "Error converting frame to BufferedImage" }
                    null
                }

                grabber.stop()
                return img!!
            }
        }
    }
}
