package org.vitrivr.engine.index.exporters

import io.github.oshai.kotlinlogging.KLogger
import io.github.oshai.kotlinlogging.KotlinLogging
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.onEach
import org.vitrivr.engine.core.context.Context
import org.vitrivr.engine.core.model.content.element.AudioContent
import org.vitrivr.engine.core.model.retrievable.Retrievable
import org.vitrivr.engine.core.operators.Operator
import org.vitrivr.engine.core.operators.OperatorFactory
import org.vitrivr.engine.core.operators.general.Exporter
import org.vitrivr.engine.core.resolver.Resolver
import org.vitrivr.engine.index.util.WaveUtilities
import java.io.IOException

private val logger: KLogger = KotlinLogging.logger {}

/**
 * An [Exporter] that generates wave files from audio samples.
 *
 * @author Ralph Gasser
 * @version 1.1.0
 */
class WaveExporter : OperatorFactory {
    /**
     * Creates a new [Instance] instance from this [ThumbnailExporter].
     *
     * @param name the name of the [ThumbnailExporter.Instance]
     * @param inputs Map of named input [Operator]s
     * @param context The [Context] to use.
     */
    override fun newOperator(name: String, inputs: Map<String, Operator<out Retrievable>>, context: Context): Operator<out Retrievable> {
        require(inputs.size == 1)  { "The ${this::class.simpleName} only supports one input operator. If you want to combine multiple inputs, use explicit merge strategies." }
        val resolverName = context[name, "resolver"] ?: "default"
        return Instance(name, inputs.values.first(), context, resolverName)
    }

    /**
     * The [Exporter] generated by this [WaveExporter].
     */
    private class Instance(
        override val name: String,
        override val input: Operator<out Retrievable>,
        private val context: Context,
        resolverName: String
    ) : Exporter {

        /** [Resolver] instance. */
        private val resolver: Resolver = this.context.resolver[resolverName]
            ?: throw IllegalStateException("Unknown resolver with name $resolverName.")

        override fun toFlow(scope: CoroutineScope): Flow<Retrievable> = this.input.toFlow(scope).onEach { retrievable ->
            try {
                val resolvable = this.resolver.resolve(retrievable.id, ".wav")
                val content = retrievable.content.filterIsInstance<AudioContent>()
                if (resolvable != null && content.isNotEmpty()) {
                    resolvable.openOutputStream().use {
                        WaveUtilities.export(content, it)
                    }
                }
            } catch (e: IOException) {
                logger.error(e) { "IO exception during wave creation." }
            }
        }
    }
}